---
title: "Tutorial1"
author: "Ximing Shen"
format: html
---

```{r}
#### Preamble ####
# Purpose: Read in data from the 2021 Canada Federal Election and make
# a graph of the number of ridings each party won.
# Author: Ximing Shen
# Email: ximing.shen@mail.utoronto.ca
# Date: 9 January 2024
# Prerequisites: ---
```

```{r}
library(tidyverse)
library(janitor)
```

```{r}
#### Simulation ####
simulated_data <-
  tibble(
    "Riding" = 1:338,
    "Party" = sample(
      x = c("Liberal", "Conservative", "Bloc Québécois", "New Democratic",
            "Green", "Other"),
      size = 338,
      replace = TRUE
    )
  )
simulated_data
```

```{r}
#### Read in the data ####
raw_elections_data <-
  read_csv(
    file = "table_tableau11.csv",
    show_col_types = FALSE,
  )
write_csv(
  x = raw_elections_data,
  file = "Canada_Federal_Election.csv"
)

head(raw_elections_data)
```
```{r}
#### Basic cleaning  ####
raw_elections_data <-
  read_csv(
    file = "Canada_Federal_Election.csv",
    show_col_types =  FALSE
  )
```

```{r}
cleaned_elections_data <-
  clean_names(raw_elections_data)
```
```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  select(electoral_district_name_nom_de_circonscription,
         elected_candidate_candidat_elu
  )
head(cleaned_elections_data)
```
```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  rename(
    riding = electoral_district_name_nom_de_circonscription,
    elected_candidate = elected_candidate_candidat_elu
  )

head(cleaned_elections_data)
```
```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  separate(
    col = elected_candidate,
    into = c("Other", "party"),
    sep = "/"
  ) |>
  select(-Other)	

head(cleaned_elections_data)
```
```{r}
cleaned_elections_data$party |>
  unique()

#### Recode Party Name ####
cleaned_elections_data <-
  cleaned_elections_data |>
  mutate(
    party =
      case_match(
        party,
        "Libéral" ~ "Liberal",
        "Conservateur" ~ "Conservative",
        "Liberal" ~ "Liberal",
        "Bloc Québécois" ~ "Bloc Québécois",
        "NPD-Nouveau Parti démocratique" ~ "New Democratic",
        "Parti Vert"  ~ "Green",
    
      )
  )

head(cleaned_elections_data)
```
```{r}
write_csv(
  x = cleaned_elections_data,
  file = "Cleaned_Canada_Federal_Election.csv"
)
```


```{r}
#### Read in the data ####
cleaned_elections_data <-
  read_csv(
    file = "Cleaned_Canada_Federal_Election.csv",
    show_col_types = FALSE
  )

cleaned_elections_data |>
  count(party)
```
```{r}
cleaned_elections_data |>
  ggplot(aes(x = party)) +
  geom_bar() +
  theme_minimal() + 
  labs(x = "Party", y = "Number of ridings")
```


